config/routes.rb
Rails.application.routes.draw do
 
  root to: redirect('/welcome')
  get 'welcome', to: 'pages#welcome', as: 'welcome'
  get 'me', to: 'pages#me', as: 'me'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
    def welcome
      render :welcome
    end
    def me
      render :me
    end
   
  end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemplateSa2Pt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/me.html.erb
<h1>My name is srija chithanoor</h1>
<p>Im a master student at university of memphis. my major-computer science and I am from india.
</p>

<p>My Hobbies are: </p>
<ul>
    <li>painting</li>
    <li>Cooking</li>
    <li>Playing Games</li>
</ul>


<%= image_tag 'srija.jpeg',class:'circle', style: 'max-width: 20rem;'%>


<p>
<%= link_to 'Back', root_path %>
</p>

app/views/pages/welcome.html.erb
<h1>Welcome to my world!!</h1>

<%= link_to 'About Me',me_path %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>